#!/bin/bash

spaces (){
  hyprctl workspaces -j | jq -rc '[.[].id | select(. > 0)] | sort_by(.) | {id:(.[]),active:false}' | jq -s . | jq -rc "(.[] | select(.id == $(hyprctl activeworkspace -j | jq -r '.name')) .active) |= true"
}

spaces
socat -u UNIX-CONNECT:/tmp/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	spaces
done
