#!/bin/bash

spaces (){
  hyprctl workspaces -j | jq -rc "[.[] | select(.id > 0)] | sort_by(.id) | .[] | {id:(.id),active:false,monitorID:(.monitorID)}" | jq -s . | jq -rc "(.[] | select(.id as \$id | ($(hyprctl monitors -j | jq -r '[.[].activeWorkspace.id]') | contains([\$id]))) .active) |= true"
}

spaces
socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	spaces
done
