#!/bin/bash

iDIR="$HOME/.config/mako/icons"

# Get Volume
get_volume() {
	volume=$(wpctl get-volume @DEFAULT_AUDIO_SINK@ | sed 's/.*Volume: //' | sed 's/ \[MUTED\].*//' | sed 's/\.//g' | sed 's/^0*//')
  if [[ "$volume" -eq "" ]]; then
    volume=0
  fi
  echo "$volume"
}

get_mic_volume() {
	volume=$(wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | sed 's/.*Volume: //' | sed 's/ \[MUTED\].*//' | sed 's/\.//g' | sed 's/^0*//')
  if [[ "$volume" -eq "" ]]; then
    volume=0
  fi
  echo "$volume"
}

# Get icons
get_icon() {
	current=$(get_volume)
	if [[ "$current" -eq "00" ]]; then
		echo "$iDIR/volume-mute.png"
	elif [[ ("$current" -ge "00") && ("$current" -le "30") ]]; then
		echo "$iDIR/volume-low.png"
	elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
		echo "$iDIR/volume-mid.png"
	elif [[ ("$current" -ge "60") ]]; then
		echo "$iDIR/volume-high.png"
	fi
}

# Notify
notify_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Volume : $(get_volume)%"
}

# Change Volume
change_volume() {
	notify_user
}

# Toggle Mute
toggle_mute() {
	if wpctl get-volume @DEFAULT_AUDIO_SINK@ | grep -q " \[MUTED\]" ; then
		notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/volume-mute.png" "Volume Switched OFF"
  else
    notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_icon)" "Volume Switched ON"
	fi
}

# Toggle Mic
toggle_mic() {
	if wpctl get-volume @DEFAULT_AUDIO_SOURCE@ | grep -q " \[MUTED\]"; then
		notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone-mute.png" "Microphone Switched OFF"
  else
		notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$iDIR/microphone.png" "Microphone Switched ON"
	fi
}
# Get icons
get_mic_icon() {
	current=$(pwctl get-volume @DEFAULT_AUDIO_SOURCE@)
	if [[ "$current" -eq "0" ]]; then
		echo "$iDIR/microphone.png"
	elif [[ ("$current" -ge "0") && ("$current" -le "30") ]]; then
		echo "$iDIR/microphone.png"
	elif [[ ("$current" -ge "30") && ("$current" -le "60") ]]; then
		echo "$iDIR/microphone.png"
	elif [[ ("$current" -ge "60") ]]; then
		echo "$iDIR/microphone.png"
	fi
}
# Notify
notify_mic_user() {
	notify-send -h string:x-canonical-private-synchronous:sys-notify -u low -i "$(get_mic_icon)" "Mic-Level : $(wpctl get-volume @DEFAULT_AUDIO_SOURCE@) %"
}

# Change MIC Volume
change_mic_volume() {
	notify_mic_user
}

# Execute accordingly
if [[ "$1" == "--get" ]]; then
	get_volume
elif [[ "$1" == "--change" ]]; then
  change_volume
elif [[ "$1" == "--inc" ]]; then
	change_volume
elif [[ "$1" == "--dec" ]]; then
	change_volume
elif [[ "$1" == "--toggle" ]]; then
	toggle_mute
elif [[ "$1" == "--toggle-mic" ]]; then
	toggle_mic
elif [[ "$1" == "--get-icon" ]]; then
	get_icon
elif [[ "$1" == "--get-mic-icon" ]]; then
	get_mic_icon
elif [[ "$1" == "--mic-change" ]]; then
  change_mic_volume
elif [[ "$1" == "--mic-inc" ]]; then
	change_mic_volume
elif [[ "$1" == "--mic-dec" ]]; then
	change_mic_volume
else
	get_volume
fi

